services:
  db-prod:
    image: postgres:16.4-bookworm
    container_name: resumequill-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Kyiv
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 10

  be-prod:
    container_name: resume-quill-be-prod
    image: resume-quill-be:prod
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db-prod:
        condition: service_healthy
    networks:
      - resume-quill-net
volumes:
  pgdata_prod:

networks:
  resume-quill-net:
    name: resume-quill-net
