services:
  db:
    image: postgres:16.4-bookworm
    container_name: resume-quill-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Kyiv
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - resume-quill-net
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  backend:
    container_name: resume-quill-be
    image: resume-quill-be:prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs/prod:/app/logs
    networks:
      - resume-quill-net
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    environment:
      - ENV=prod
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    privileged: true
    networks:
      - resume-quill-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - lokidata:/loki
    networks:
      - resume-quill-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheusdata:/prometheus
    networks:
      - resume-quill-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    networks:
      - resume-quill-net

volumes:
  pgdata:
    external: true
    name: pgdata_prod
  grafanadata:
    external: true
    name: grafana_data_prod
  lokidata:
    external: true
    name: loki_data_prod
  prometheusdata:
    external: true
    name: prometheus_data_prod

networks:
  resume-quill-net:
    name: resume-quill-net
