services:
  db:
    container_name: resumequill_db_dev
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
#  app:
#    container_name: resume-quill-be-dev
#    image: resume-quill-be:dev
#    build: .
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env.dev
#    environment:
#      DB_URL: ${DB_URL}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      JWT_SECRET: ${JWT_SECRET}
#      JWT_EXPIRATION: ${JWT_EXPIRATION}
#    depends_on:
#      db:
#        condition: service_healthy
