services:
  db:
    container_name: resume-quill-db-dev
    env_file:
      - .env.dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
  app:
    container_name: resume-quill-be-dev
    image: resume-quill-be:dev
    restart: unless-stopped
    build: .
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - .env.dev
volumes:
  pgdata_dev:
