services:
  db-dev:
    image: postgres:16.4-bookworm
    container_name: resume-quill-db-dev
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Kyiv
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
  be-dev:
    container_name: resume-quill-be-dev
    image: resume-quill-be:dev
    restart: unless-stopped
    build: .
    depends_on:
      db-dev:
        condition: service_healthy
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - .env.dev
volumes:
  pgdata_dev:
