services:
  db:
    container_name: resume-quill-db-dev
    ports:
      - "127.0.0.1:5434:5432"

  backend:
    container_name: resume-quill-be-dev
    image: resume-quill-be:dev
    env_file:
      - .env.dev
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./logs/dev:/app/logs

  grafana:
    container_name: grafana-dev
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./grafana/provisioning/datasources/datasources-dev.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro

  prometheus:
    container_name: prometheus-dev
    volumes:
      - ./prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  pgdata:
    name: pgdata_dev
  grafanadata:
    name: grafanadata_dev
  lokidata:
    name: lokidata_dev
  prometheusdata:
    name: prometheusdata_dev

networks:
  resume-quill-net:
    name: resume-quill-dev-net
