services:
  db:
    container_name: resume-quill-db-dev
    ports:
      - "127.0.0.1:5434:5432"

  backend:
    container_name: resume-quill-be-dev
    image: resume-quill-be:dev
    env_file:
      - .env.dev
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./logs/dev:/app/logs

  promtail:
    container_name: promtail-dev
    environment:
      - ENV=dev
    ports:
      - "127.0.0.1:9081:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true

  loki:
    container_name: loki-dev
    ports:
      - "127.0.0.1:3101:3100"

  prometheus:
    container_name: prometheus-dev
    ports:
      - "127.0.0.1:9091:9090"
    volumes:
      - ./prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana-dev
    volumes:
      - ./grafana/provisioning/datasources/datasources-dev.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    ports:
      - "127.0.0.1:3001:3000"

volumes:
  pgdata:
    name: pgdata_dev
  grafanadata:
    name: grafanadata_dev
  lokidata:
    name: lokidata_dev

networks:
  resume-quill-net:
    name: resume-quill-dev-net
