services:
  db-local:
    image: postgres:16.4-bookworm
    container_name: resume-quill-db-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Kyiv
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "127.0.0.1:5433:5432"
volumes:
  pgdata_local:
