apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki-local:3100
    isDefault: true
    editable: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-local:9090
    editable: false
