scrape_configs:
  - job_name: resume-quill
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        regex: resumequill-be-${ENV:-prod}
        action: keep

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: backend
        action: keep

      - source_labels: [__meta_docker_container_name]
        target_label: container

      - target_label: env
        replacement: ${ENV:-prod}

      - target_label: service_name
        replacement: resume-quill-be

    pipeline_stages:
      - docker: {}

      - json:
          expressions:
            level: level
            method: method

      - labels:
          level:
          method:
