server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: resume-quill
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # только backend-сервис
      - source_labels: [ __meta_docker_compose_service ]
        regex: backend
        action: keep

      - source_labels: [ __meta_docker_container_name ]
        target_label: container

      - target_label: env
        replacement: ${ENV:-prod}

      - target_label: service_name
        replacement: resume-quill-be

    pipeline_stages:
      - docker: { }

      - json:
          expressions:
            level: level
            message: message
            requestId: requestId
            method: method
            path: path
            userId: userId

      - labels:
          level:
          method:

      - output:
          source: message
